### ISSUE TITLE
Avoid applying unintended labels when transferring issues

### ISSUE THREAD

**Issue by jeffhandley** [dotnet/perf-autofiling-issues#3836]
As @teo-tsirpanis noted in [this comment](https://github.com/dotnet/runtime/issues/62032#issuecomment-1042913605), when issues get transferred from this repository into dotnet/runtime, some unintended labels are getting created in the dotnet/runtime repo. Is this something we can avoid easily?

**Comment by teo-tsirpanis** [comment]
Issue transfers could be performed by a bot command that first removes labels that don't exist in the target repository.
